Shorthands
wixplosives/toky pull request #4
Opened 2021-02-18 11:33 UTC by talh78

2021-02-18 13:54 UTC, danieleww approved these changes

2021-02-18 13:54 UTC, danieleww commented on src/shorthands/openers/background-shorthand.ts
> +} as ShorthandPart<string>].concat(bgLayerShorthandParts);
no need for ```as ShorthandPart<string>```

2021-02-18 13:54 UTC, danieleww commented on src/shorthands/shorthand-parser-utils.ts
> +    opened[prop] = getDefaultAst(keywordValues[prop as T]);
no need for ```as T```

2021-02-18 13:54 UTC, danieleww commented on src/shorthands/openers/font-shorthand.ts
> +        ) as Record<FontPrefixes, EvaluatedAst>,
no need for ```as Record<... ```

2021-02-18 13:54 UTC, danieleww commented on src/shorthands/openers/font-shorthand.ts
> +        ) as Record<FontSuffixes, EvaluatedAst>,
same

2021-02-21 12:35 UTC, barak007 requested changes
This PR should be extracted to a separate repo. 
The tokenizer abilities can stay but any shorthand expansion must go.

2021-02-24 13:44 UTC, talh78 commented
Code moved to a new repository [here](https://github.com/wixplosives/shorthands-opener)

2021-03-02 09:24 UTC, closed without merging